name: muscle_up
description: "Next-gen Fitness App. New height, New companions."
publish_to: 'none' 
version: 0.1.0

environment:
  sdk: ^3.8.0 # Або ваша актуальна версія Dart SDK

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.8
  animated_background: ^2.0.0 # Для LoginPage
  flutter_bloc: ^9.1.1 # Або ваша версія
  bloc: 9.0.0 # Додайте або перевірте наявність цієї залежності (версія може відрізнятися)
  equatable: ^2.0.5
  intl: ^0.19.0 # Для форматування дати/часу
  
  # Додані пакети для WorkoutCompleteScreen
  confetti: ^0.7.0 # Або актуальна версія
  lottie: ^3.1.2 # Або актуальна версія

  # Додано для колекцій (може знадобитися для firstWhereOrNull, хоча часто є в SDK)
  # collection: ^1.18.0 # Якщо ви використовуєте specific collection utilities

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Або актуальна версія
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true               
  image_path: "assets/images/app_icon.png" 
  min_sdk_android: 23  
  # web:
  #   generate: true
  #   image_path: "assets/images/app_icon_web.png"
  #   background_color: "#ED5D1A" 
  #   theme_color: "#ED5D1A"     
  # windows:
  #   generate: true
  #   image_path: "assets/images/app_icon_windows.png"
  #   icon_size: 48 
  # macos:
  #   generate: true
  #   image_path: "assets/images/app_icon_macos.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/fonts/ 
    - assets/animations/ # <--- ДОДАНО ДЛЯ LOTTIE АНІМАЦІЙ

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
          
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
          weight: 700