name: muscle_up
description: "Next-gen Fitness App. New height, New companions."
publish_to: 'none' 
version: 0.9.9

environment:
  sdk: ^3.8.0 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter         
  
  # Firebase SDK
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.1.0 

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  
  # Utilities
  equatable: ^2.0.5
  intl: ^0.20.2 
  image_picker: ^1.1.2 
  image_cropper: ^9.1.0 

  # Graphics & Animations
  flutter_svg: ^2.0.10+1
  animated_background: ^2.0.0
  confetti: ^0.7.0
  lottie: ^3.1.2
  shared_preferences: ^2.5.3
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0 # <--- ДОДАНО ПАКЕТ

# Конфігурація для іконки додатку
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 23

# Конфігурація для екрану-заставки (splash screen)
flutter_native_splash:
  # Замість простого кольору, ми використовуємо фонове зображення, яке є градієнтом.
  background_image: "assets/images/splash_gradient_background.png"
  background_image_dark: "assets/images/splash_gradient_background_dark.png" # Опціонально, для темної теми

  # Логотип, що буде відображатися ПОСЕРЕДИНІ поверх градієнтного фону.
  image: "assets/images/splash_logo.png"
  image_dark: "assets/images/splash_logo_dark.png" # Опціонально, для темної теми

  # Налаштування для Android 12+ (дуже важливо)
  android_12:
    # Іконка для Android 12+ (зазвичай, та сама, що іконка додатку)
    image: "assets/images/app_icon.png" 
    
    # Колір фону ПІД іконкою. Використайте основний колір вашого градієнту.
    icon_background_color: "#ED5D1A" # Помаранчевий
    
    image_dark: "assets/images/app_icon.png"
    icon_background_color_dark: "#C70039" # Темно-червоний (кінцевий колір градієнту)


flutter:
  uses-material-design: true
  generate: true 

  assets:
    - assets/images/
    - assets/images/achievements/
    - assets/images/male_front.svg 
    - assets/images/male_back.svg
    - assets/images/female_front.svg
    - assets/images/female_back.svg
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
          
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
          weight: 700